# Generated by Django 4.1.7 on 2023-04-11 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_manager', '0009_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('hardware_serial', models.CharField(max_length=200)),
                ('software_serial', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_manager.equipcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_image', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('ready_excellent', '可发货(好)'), ('ready_good', '可发货(中)'), ('ready', '可发货'), ('ready_confirm', '可发货，需确认'), ('under_maintain', '检修中'), ('ordered', '已订货'), ('sold', '已售出')], max_length=100)),
                ('inbound_date', models.DateField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='presale.equipment')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintain_devices', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operate_devices', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='info_manager.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
