# Generated by Django 4.1.7 on 2023-04-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0003_suppier_alter_device_warehouse_equipment_suppier'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
