# Generated by Django 4.1.7 on 2023-04-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0005_inbound_device_inbount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='inbount',
            new_name='inbound',
        ),
    ]
