# Generated by Django 4.1.7 on 2023-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presale", "0010_device_is_sold_alter_device_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="state",
            field=models.CharField(
                choices=[
                    ("ready_excellent", "可发货(好)"),
                    ("ready_good", "可发货(中)"),
                    ("ready", "可发货"),
                    ("ready_confirm", "可发货，需确认"),
                ],
                max_length=100,
            ),
        ),
    ]
