# Generated by Django 4.1.7 on 2023-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presale", "0011_alter_device_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
