# Generated by Django 4.1.7 on 2023-02-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0002_module_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parent_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_manager.module'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_manager.role'),
        ),
    ]
