# Generated by Django 4.1.7 on 2023-03-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0004_module_icon_module_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
