# Generated by Django 4.1.7 on 2023-04-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0005_alter_module_icon_alter_module_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='EquipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manager.equipcategory')),
            ],
        ),
    ]
