# Generated by Django 4.1.7 on 2023-04-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0006_alter_module_options_equipcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipcategory',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_manager.equipcategory'),
        ),
    ]
