# Generated by Django 4.1.7 on 2023-04-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0007_alter_equipcategory_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipcategory',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
