# Generated by Django 4.1.7 on 2023-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0008_rename_parent_id_equipcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
