# Generated by Django 4.1.7 on 2023-05-23 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("presale", "0009_alter_device_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintainance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintainancerecord",
            name="device",
        ),
        migrations.CreateModel(
            name="DeviceMalfuntionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="presale.device",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintainancerecord",
            name="malfunction_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintainance.devicemalfuntionrecord",
            ),
        ),
    ]
