# Generated by Django 4.1.7 on 2023-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0002_remove_maintainancerecord_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemalfuntionrecord",
            name="dispatch_date",
            field=models.DateField(null=True),
        ),
    ]
