# Generated by Django 4.1.7 on 2023-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0003_devicemalfuntionrecord_dispatch_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemalfuntionrecord",
            name="is_finished",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
