# Generated by Django 4.1.7 on 2023-06-02 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0005_remove_devicemalfuntionrecord_is_finished_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintainancerecord",
            name="maintainer",
        ),
    ]
