# Generated by Django 4.1.7 on 2023-06-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0006_remove_maintainancerecord_maintainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintainancerecord",
            name="malfunction_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintainance_records",
                to="maintainance.devicemalfuntionrecord",
            ),
        ),
    ]
