# Generated by Django 4.1.7 on 2023-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0007_alter_maintainancerecord_malfunction_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintainancerecord",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
