# Generated by Django 4.1.7 on 2023-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintainance", "0008_alter_maintainancerecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemalfuntionrecord",
            name="state",
            field=models.CharField(
                choices=[
                    ("assigned", "已分配"),
                    ("started", "已开始检修"),
                    ("finished", "已完成"),
                ],
                default="assigned",
                max_length=50,
            ),
        ),
    ]
