# Generated by Django 4.1.7 on 2023-04-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presale', '0002_alter_device_inbound_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=300)),
                ('memo', models.CharField(max_length=1000)),
                ('pay_method', models.CharField(choices=[('instant_pay', '立即结算'), ('month_pay', '按月结算'), ('season_pay', '按季度结算'), ('year_pay', '按年结算')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_date', models.DateField()),
                ('outbound_image', models.ImageField(upload_to='')),
                ('fix_address', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_state', models.CharField(choices=[('paid', '已结算'), ('unpaid', '未结算')], max_length=30)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_bought', to='postsale.client')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='presale.device')),
                ('outbound_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_sold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
