# Generated by Django 4.1.7 on 2023-04-13 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesold',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
