# Generated by Django 4.1.7 on 2023-04-19 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0002_devicesold_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesold',
            name='state',
            field=models.CharField(choices=[('good', '正常'), ('bad', '故障'), ('maintaining', '检修中')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devicesold',
            name='outbound_image',
            field=models.ImageField(upload_to='outbound-images/'),
        ),
        migrations.AlterField(
            model_name='devicesold',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 4, 19)),
        ),
    ]
