# Generated by Django 4.1.7 on 2023-04-28 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0005_alter_outbound_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='outbound_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='outbound_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 4, 28)),
        ),
    ]
