# Generated by Django 4.1.7 on 2023-05-03 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0006_alter_outbound_outbound_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 5, 3)),
        ),
    ]
