# Generated by Django 4.1.7 on 2023-05-09 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0007_alter_outbound_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pay_method',
        ),
        migrations.AlterField(
            model_name='outbound',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 5, 9)),
        ),
    ]
