# Generated by Django 4.1.7 on 2023-05-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0008_remove_client_pay_method_alter_outbound_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='pay_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
