# Generated by Django 4.1.7 on 2023-05-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("presale", "0011_alter_device_state"),
        ("postsale", "0010_alter_devicesold_state_alter_outbound_pay_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesold",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_sold",
                to="presale.device",
            ),
        ),
    ]
